apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: normalizer
    component: kafka-streams
  name: normalizer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: normalizer
        component: kafka-streams
    spec:
      containers:
      - name: normalizer
        image: normalizer:latest
        env:
          - name: APPLICATION_ID
            value: "my-kubernetes-normalizer-id"
          - name: KAFKA_BOOTSTRAP_SERVER
            value: kafka:9092
          - name: ZOOKEEPER_CONNECT
            value: zookeeper-svc:2181
          - name: NUM_STREAM_THREADS
            value: "1"
          - name: METRIC_ENABLE
            value: "true"
          - name: MULTI_ID
            value: "false"
