# Site theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "wizzie"

# Site Settings
locale: "en-US"
title: 'Normalizer'
title_separator: "-"
name: 'Wizzie Analytics'
baseurl: '/normalizer'
description: 'Normalizer is a stream processing engine based of Kafka Streams. Normalizer does maps (stateless and stateful), flatmaps and filters by us. You only need to define a JSON stream where you specify the process logic and how the messages are transformed.'
repository: 'wizzie-io/normalizer'

# Site search
search: true
search_provider: google
search_full_content: true

google:
  search_engine_id: 015992723382350682522:4u8h3rlqahc
  instant_search: true

google_site_verification: MjIfY0_y_7qIgMjaLFMggPJaLitLhygQ3eodF9Y5ITY

# Social Sharing
twitter:
  username: &twitter "wizzieio"
og_image: '/assets/images/logo.png'

defaults:
  # _docs
  - scope:
      path: ""
    values:
      toc_sticky: true
      sidebar:
        nav: "docs"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/wizzieio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wizzie-io"
